### ISSUE TITLE
Error: "None of ['WhiteListMatch'] are in the columns"Traceback:

### ISSUE THREAD

**Issue by Selecton98** [landau-lab/Gotcha#11] opened 2024-05-23 20:30 UTC
Hello the Gotcha authors,

I'm trying your genotyping algorithm and encounter the following error:

"None of ['WhiteListMatch'] are in the columns"

Traceback:

1. GotchaLabeling(path = "[/lab-share/Public/data/DNV/barcode3/](http://compute:8889/lab/tree/data/DNV/barcode3/data/DNV/barcode3/)", 
 .     infile = "Genemeta.csv", gene_id = "Gene", sample_id = "RM30")
2. reticulate::import_from_path(module = "gotcha_labeling", path = find.package("Gotcha"))$GotchaLabeling(path = path, 
 .     infile = infile, gene_id = gene_id, sample_id = sample_id)
3. py_call_impl(callable, call_args$unnamed, call_args$named)

My file has a format matching your demo:
<img width="995" alt="image" src="https://github.com/landau-lab/Gotcha/assets/51666666/b464cd35-3c32-422e-8402-4dc906443111">

Could you please tell me in which file should I  'WhiteListMatch' 
Thank you,
Sunny

**Comment by fizzo13** [comment] 2024-05-23 20:37
Hi Sunny, thank you for using GoTChA. Can you try replacing the column name from 'X' to "WhiteListMatch"?
Tagging @SanjayKottapalli for help with the python module.

**Comment by Selecton98** [comment] 2024-05-23 21:01
> Hi Sunny, thank you for using GoTChA. Can you try replacing the column name from 'X' to "WhiteListMatch"? Tagging @SanjayKottapalli for help with the python module.

Hello! Thank you for the reply. I tried to change 'X' to 'WhiteListMatch' in the list but it didn't help.
@SanjayKottapalli

**Comment by SanjayKottapalli** [comment] 2024-05-23 21:06
Hi Sunny, I think the issue is actually with the "gene_id" and "sample_id" parameters that you set. Can you show me exactly how your own input .csv file looks?

**Comment by Selecton98** [comment] 2024-05-24 19:22
[Genemeta.csv](https://github.com/landau-lab/Gotcha/files/15439108/Genemeta.csv)
@SanjayKottapalli
Please find my file in the attachment. I used "RM30" to make this column same as your demo (for easier debugging).
Thank you for your help!

**Comment by SanjayKottapalli** [comment] 2024-05-24 20:27
Hmm, I tried to read the file in python and it worked just fine for me. Can you try the following?

In an interactive python session:
1. Navigate to the folder where you installed Gotcha, then cd into inst/python
2. `import gotcha_labeling`
3. `test = gotcha_labeling.read_data("/lab-share/Public/data/DNV/barcode3/Genemeta.csv", "Gene", "RM30")`
4. `print(test)`

Let me know what output this gives and if any errors come up.

**Comment by Selecton98** [comment] 2024-05-24 22:11
<img width="444" alt="image" src="https://github.com/landau-lab/Gotcha/assets/51666666/8d7cbbf7-d201-4eb2-880f-aee01fe23251">
@SanjayKottapalli
The files is successfully read by the "gotcha_labeling.read_data".

**Comment by fizzo13** [comment] 2024-05-28 20:05
@Selecton98 was the issue fixed?

**Comment by SanjayKottapalli** [comment] 2024-05-28 20:13
Since it seems to be working when using python only and doesn't work when you call python through the R pipeline, it seems like it could be a reticulate issue @fizzo13 . Probably related to formatting of dataframes. 

@Selecton98 could you also try commenting/changing this code in your gotcha_labeling.py from

>    try:
>         genotyping = pd.DataFrame(index=cell_line.index)
>         if sample_id in np.unique(cell_line['Sample'].values):
>             cell_line = cell_line.loc[cell_line['Sample']==sample_id, :]
>         genotyping['WTcount'] = cell_line[gene_id+'_WTcount']
>         genotyping['MUTcount'] = cell_line[gene_id+'_MUTcount']
>     except:
>         cell_line = cell_line.set_index("WhiteListMatch")
>         genotyping = pd.DataFrame(index=cell_line.index)
>         genotyping['WTcount'] = cell_line['WTcount']
>         genotyping['MUTcount'] = cell_line['MUTcount']

to only what's in the try block?

> genotyping = pd.DataFrame(index=cell_line.index)
> if sample_id in np.unique(cell_line['Sample'].values):
>      cell_line = cell_line.loc[cell_line['Sample']==sample_id, :]
> genotyping['WTcount'] = cell_line[gene_id+'_WTcount']
> genotyping['MUTcount'] = cell_line[gene_id+'_MUTcount']

  
  The error is strange because the try block shouldn't fail to begin with.

**Comment by Selecton98** [comment] 2024-05-29 13:16
@SanjayKottapalli 
@fizzo13 
Hi everyone, 
I finally get this bug solved.

One problem is the R "GotchaLabeling" doesn't need a "sample_column" information which is required by the python "GotchaLabeling" and "read_data". So I manually defined "sample_column='Sample'" in each of these two functions.

Another problem is the csv file should include an index column and a "WhiteListMatch" column. Both of these two columns should be index/barcode information.

Thank you,
Sunny

**Comment by fizzo13** [comment] 2024-05-29 15:27
Thank you @SanjayKottapalli and @Selecton98 . I'll close the issue.

**Closed as completed by fizzo13** 2024-05-29 15:27 UTC
